name: HayrXVPN

targets:
  HayrXVPN:
    type: application
    platform: iOS
    sources: [App, Shared]
    settings:
      base:
        PRODUCT_NAME: HayrXVPN
        PRODUCT_BUNDLE_IDENTIFIER: com.hayrxvpn.ios
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/HayrXVPN.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: YOUR_TEAM_ID
    dependencies:
      - target: HayrXVPNTunnel
        embed: true

  HayrXVPNTunnel:
    type: app-extension
    platform: iOS
    sources: [VPNTunnelExtension, Shared]
    settings:
      base:
        PRODUCT_NAME: HayrXVPNTunnel
        PRODUCT_BUNDLE_IDENTIFIER: com.hayrxvpn.ios.tunnel
        INFOPLIST_FILE: VPNTunnelExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: VPNTunnelExtension/HayrXVPNTunnel.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: YOUR_TEAM_ID
